- name: nginx_repo
  copy:
     dest: /etc/yum.repos.d/nginx.repo
     content:
      '[nginx-stable]
      name=nginx stable repo
      baseurl=http://nginx.org/packages/centos/\$releasever/\$basearch/
      gpgcheck=1
      enabled=1
      gpgkey=https://nginx.org/keys/nginx_signing.key
      module_hotfixes=true
      
      [nginx-mainline]
      name=nginx mainline repo
      baseurl=http://nginx.org/packages/mainline/centos/\$releasever/\$basearch/
      gpgcheck=1
      enabled=0
      gpgkey=https://nginx.org/keys/nginx_signing.key
      module_hotfixes=true'
- name: add packages
  ansible.builtin.yum:
    name:
#    - EPEL_RELEASE
#    - CIVENTY_RELEASE
    - mc
    - htop 
    - iotop 
    - atop 
    - dstat 
    - bwm-ng 
    - exim 
    - rsync 
    - logwatch 
    - smartmontools 
    - lsof 
    - tcpdump 
    - unzip 
    - pciutils 
    - mcelog 
    - net-tools 
    - glances 
    - iptables-services 
    - irqbalance 
    - tmux 
    - psmisc 
    - chrony 
    - bzip2 
    - firewalld 
    - yum-utils
    state: present
